name: perch_care
description: "AI 기반 반려동물 건강 관리 앱"
publish_to: "none"
version: 1.0.1+2

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.10+1
  go_router: ^14.6.2
  fl_chart: ^0.68.0
  flutter_dotenv: ^5.1.0
  http: ^1.2.2
  shared_preferences: ^2.3.2
  country_picker: ^2.0.26
  image_picker: ^1.2.1
  flutter_secure_storage: ^10.0.0
  sqflite: ^2.4.1
  sqflite_common_ffi: ^2.3.4+4
  path_provider: ^2.1.5
  path: ^1.9.0
  google_sign_in: ^7.2.0
  sign_in_with_apple: ^7.0.1
  kakao_flutter_sdk_user: 1.9.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/app_icon_1024_flat.png"
  remove_alpha_ios: true

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - .env
    - assets/images/login_vector/
    - assets/images/btn_google/
    - assets/images/btn_apple/
    - assets/images/btn_naver/
    - assets/images/btn_kakao/
    - assets/images/signup_vector/
    - assets/images/home_vector/
    - assets/images/profile/
